// generated by mBlock5 for <your product>
// codes make you happy

#include "Matrix.h"

//#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

Matrix myMatrix(A4,A5);

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  myMatrix.begin(0x70);
  myMatrix.clear();
  while(1) {
      myMatrix.displaybuffer[0]=0B0011111100111100;
      myMatrix.displaybuffer[1]=0B0100000001000010;
      myMatrix.displaybuffer[2]=0B1001111010011001;
      myMatrix.displaybuffer[3]=0B1010000110100101;
      myMatrix.displaybuffer[4]=0B1010010110100001;
      myMatrix.displaybuffer[5]=0B1001100110011110;
      myMatrix.displaybuffer[6]=0B0100001001000000;
      myMatrix.displaybuffer[7]=0B0011110000111111;
      myMatrix.writeDisplay();
      _delay(1);
      myMatrix.displaybuffer[0]=0B1000000000000000;
      myMatrix.displaybuffer[1]=0B1000111000000000;
      myMatrix.displaybuffer[2]=0B0101000000001110;
      myMatrix.displaybuffer[3]=0B0001011000010000;
      myMatrix.displaybuffer[4]=0B0001000000010110;
      myMatrix.displaybuffer[5]=0B0000111001010000;
      myMatrix.displaybuffer[6]=0B0000000010001110;
      myMatrix.displaybuffer[7]=0B0000000010000000;
      myMatrix.writeDisplay();
      _delay(1);

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}
